 * Serving Flask app "word2vec" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:6000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 274-334-178
127.0.0.1 - - [22/Mar/2021 03:59:05] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/data/judel/anaconda38/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zhaoyuc2/word2vec/word2vec.py", line 46, in hello
    return render_template('index.html', models=modelList())
  File "/home/zhaoyuc2/word2vec/word2vec.py", line 37, in modelList
    for f in sorted(os.listdir(model_base)):
FileNotFoundError: [Errno 2] No such file or directory: '../../../srv/data/judel/models/'
127.0.0.1 - - [22/Mar/2021 03:59:05] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [22/Mar/2021 03:59:05] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [22/Mar/2021 03:59:05] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [22/Mar/2021 03:59:05] "[37mGET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [22/Mar/2021 03:59:06] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [22/Mar/2021 03:59:06] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
